# Site settings
title: "A Y C H L O V E"
description: 'Read AYCHLOVE in plain text online.

The AYCHLOVE is a fresh version of accessing the participation of AYCH inc to social development program. This is a manual, step-by-step guide, towards its engagement and practices. It is meant to be practical. It is meant for use of human being.'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aychlove.github.io" # the base hostname & protocol for your site
github_username: Creditbox
github_url:  https://github.com/aychlove/aychlove.io
permalink: pretty
exlude:
  - css/style.styl
  - Gemfile
  - Gemfile.lock
  - README.md
  - working/

# Build settings
markdown: kramdown
